language: python

notifications:
  irc: "chat.freenode.net#pil"

python:
  - "pypy"
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

before_install:
  - time curl -O http://sipi.usc.edu/database/aerials.tar.gz
  - time tar -zxvf aerials.tar.gz
  - time curl -O http://sipi.usc.edu/database/misc.tar.gz
  - time tar -zxvf misc.tar.gz
  - time curl -O http://sipi.usc.edu/database/sequences.tar.gz
  - time tar -zxvf sequences.tar.gz
  - time curl -O http://sipi.usc.edu/database/textures.tar.gz
  - time tar -zxvf textures.tar.gz
  # - time wget -o testimages.zip http://sourceforge.net/projects/testimages/files/SAMPLING/testimages.zip/download
  # - time unzip -q testimages.zip


install:
  - "sudo apt-get -qq install libfreetype6-dev liblcms2-dev python-qt4 ghostscript libffi-dev cmake"
  - "pip install cffi"
  - "pip install coveralls"

  # webp
  - pushd depends && ./install_webp.sh && popd

  # openjpeg
  - pushd depends && ./install_openjpeg.sh && popd

script:
  - coverage erase
  - python setup.py clean
  - python setup.py build_ext --inplace
  - coverage run --append --include=PIL/* selftest.py
  - python Tests/run.py --coverage

after_success:
  - coverage report
  - coveralls
  - pip install pep8 pyflakes
  - pep8 PIL/*.py
  - pyflakes PIL/*.py

matrix:
  allow_failures:
    - python: "pypy"
    - python: 3.4
